"""Added Product Model

Revision ID: 26ddf466594c
Revises: d2075b80b966
Create Date: 2023-12-14 16:08:59.768427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ddf466594c'
down_revision = 'd2075b80b966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
